// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHrwSQw8t2ULKpSY6PAiWX6UiydcG1in8',
    appId: '1:70475374926:web:390b09c5ee43167df4fe1f',
    messagingSenderId: '70475374926',
    projectId: 'blooddonationbank-50f9b',
    authDomain: 'blooddonationbank-50f9b.firebaseapp.com',
    storageBucket: 'blooddonationbank-50f9b.appspot.com',
    measurementId: 'G-2C3TZ6W73F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kxtFIPjhzAe1jtNm7z-Qq_czKEYCNJM',
    appId: '1:70475374926:android:fb8b5b0172d4807cf4fe1f',
    messagingSenderId: '70475374926',
    projectId: 'blooddonationbank-50f9b',
    storageBucket: 'blooddonationbank-50f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB50AXCPtnEk8edETToaYXUhg4jRZrruYk',
    appId: '1:70475374926:ios:61319957f82aca50f4fe1f',
    messagingSenderId: '70475374926',
    projectId: 'blooddonationbank-50f9b',
    storageBucket: 'blooddonationbank-50f9b.appspot.com',
    iosBundleId: 'com.example.bloodDonationBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB50AXCPtnEk8edETToaYXUhg4jRZrruYk',
    appId: '1:70475374926:ios:589a2d645b76e0adf4fe1f',
    messagingSenderId: '70475374926',
    projectId: 'blooddonationbank-50f9b',
    storageBucket: 'blooddonationbank-50f9b.appspot.com',
    iosBundleId: 'com.example.bloodDonationBank.RunnerTests',
  );
}
